name: CI

on:
  pull_request:

permissions:
  contents: read

jobs:
  rspec:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler: '1.17.3'
      - run: bundle install --without development
      - run: bundle exec rake spec
